/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ensambladora.de.maquinas;

import java.sql.CallableStatement;
import java.sql.ResultSet;
import java.sql.*;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;

/**
 *
 * @author Francisco Santos
 */
public class Principal extends javax.swing.JFrame {

    private Connection cn;
    private String cadena = "jdbc:sqlserver://localhost:1433;databaseName=compañia";
    private String usuario = "sa";
    private String pass = "Darielleo1989";

    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_Proveedor = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_IdProveedor = new javax.swing.JTextField();
        tf_NombreProv = new javax.swing.JTextField();
        cb_Proveedor = new javax.swing.JComboBox<>();
        jb_AgregarProv = new javax.swing.JButton();
        jd_Comercio = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_NumComercio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_NomComercio = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tf_Recaudacion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cb_Provee = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        sp_Ingreso = new javax.swing.JSpinner();
        jb_AgregarComercio = new javax.swing.JButton();
        jd_Producto = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tf_IDProducto = new javax.swing.JTextField();
        tf_Marca = new javax.swing.JTextField();
        tf_Material = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jd_Maquina = new javax.swing.JDialog();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tf_NumSerie = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        cb_Estado = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        tf_IDPlaca = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        tf_IDCarcasa = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        tf_NumReparacion = new javax.swing.JTextField();
        bt_AgregarMaquina = new javax.swing.JButton();
        jd_Tecnico = new javax.swing.JDialog();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        tf_IDTecnico = new javax.swing.JTextField();
        tf_NomTecnico = new javax.swing.JTextField();
        tf_NumRepTecnico = new javax.swing.JTextField();
        bt_AgregarTecnico = new javax.swing.JButton();
        sp_Fallo = new javax.swing.JSpinner();
        jd_Reparacion = new javax.swing.JDialog();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        bt_AgregarReparacion = new javax.swing.JButton();
        cb_IDTecnico = new javax.swing.JComboBox<>();
        cb_NumReparaciones = new javax.swing.JComboBox<>();
        jd_Alquiler = new javax.swing.JDialog();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        cb_SerieAlquiler = new javax.swing.JComboBox<>();
        cb_ComercioAlquiler = new javax.swing.JComboBox<>();
        bt_AgregarAlquiler = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jb_Proveedor = new javax.swing.JButton();
        jb_Producto = new javax.swing.JButton();
        jb_Comercio = new javax.swing.JButton();
        jb_Tecnico = new javax.swing.JButton();
        jb_Maquina = new javax.swing.JButton();
        jb_Reparacion = new javax.swing.JButton();
        jb_Alquiler = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("MS UI Gothic", 0, 48)); // NOI18N
        jLabel2.setText("Proveedor");

        jLabel3.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        jLabel3.setText("ID  Proveedor");

        jLabel4.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        jLabel4.setText("Nombre Proveedor");

        jLabel5.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        jLabel5.setText("Proveedor Placas");

        tf_IdProveedor.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N

        tf_NombreProv.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N

        cb_Proveedor.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        cb_Proveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Placas", "Carcasas" }));

        jb_AgregarProv.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        jb_AgregarProv.setText("Agregar");
        jb_AgregarProv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_AgregarProvMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_ProveedorLayout = new javax.swing.GroupLayout(jd_Proveedor.getContentPane());
        jd_Proveedor.getContentPane().setLayout(jd_ProveedorLayout);
        jd_ProveedorLayout.setHorizontalGroup(
            jd_ProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ProveedorLayout.createSequentialGroup()
                .addGroup(jd_ProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ProveedorLayout.createSequentialGroup()
                        .addGap(453, 453, 453)
                        .addComponent(jLabel2))
                    .addGroup(jd_ProveedorLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addGroup(jd_ProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(144, 144, 144)
                        .addGroup(jd_ProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_IdProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_NombreProv, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_Proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_ProveedorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jb_AgregarProv, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
        );
        jd_ProveedorLayout.setVerticalGroup(
            jd_ProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ProveedorLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel2)
                .addGap(160, 160, 160)
                .addGroup(jd_ProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_IdProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(jd_ProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_NombreProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(129, 129, 129)
                .addGroup(jd_ProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cb_Proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addComponent(jb_AgregarProv, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        jLabel6.setFont(new java.awt.Font("MS UI Gothic", 0, 36)); // NOI18N
        jLabel6.setText("Comercio");

        jLabel7.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        jLabel7.setText("Numero de Comercio");

        tf_NumComercio.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N

        jLabel8.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        jLabel8.setText("Nombre de Comercio");

        tf_NomComercio.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N

        jLabel9.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        jLabel9.setText("Recaudacion Total");

        tf_Recaudacion.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N

        jLabel10.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        jLabel10.setText("Provee");

        cb_Provee.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        cb_Provee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mayorista", "Minorista" }));
        cb_Provee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_ProveeActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        jLabel11.setText("Porcentaje Ingreso");

        sp_Ingreso.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        sp_Ingreso.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 5));

        jb_AgregarComercio.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        jb_AgregarComercio.setText("Agregar");
        jb_AgregarComercio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_AgregarComercioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_ComercioLayout = new javax.swing.GroupLayout(jd_Comercio.getContentPane());
        jd_Comercio.getContentPane().setLayout(jd_ComercioLayout);
        jd_ComercioLayout.setHorizontalGroup(
            jd_ComercioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ComercioLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jd_ComercioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ComercioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(jd_ComercioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ComercioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6)
                        .addComponent(tf_NumComercio)
                        .addComponent(tf_NomComercio)
                        .addComponent(tf_Recaudacion)
                        .addComponent(cb_Provee, 0, 289, Short.MAX_VALUE))
                    .addComponent(sp_Ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(217, 217, 217))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_ComercioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_AgregarComercio, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        jd_ComercioLayout.setVerticalGroup(
            jd_ComercioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ComercioLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel6)
                .addGap(121, 121, 121)
                .addGroup(jd_ComercioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_NumComercio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addGroup(jd_ComercioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_NomComercio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addGroup(jd_ComercioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_Recaudacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(jd_ComercioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cb_Provee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(jd_ComercioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(sp_Ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_AgregarComercio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jLabel12.setFont(new java.awt.Font("MS UI Gothic", 0, 48)); // NOI18N
        jLabel12.setText("Producto");

        jLabel13.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        jLabel13.setText("ID Producto");

        jLabel14.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        jLabel14.setText("Marca");

        jLabel15.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        jLabel15.setText("Material");

        jLabel16.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        jLabel16.setText("ID Proveedor");

        tf_IDProducto.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N

        tf_Marca.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N

        tf_Material.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N

        jButton1.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        jButton1.setText("Agregar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_ProductoLayout = new javax.swing.GroupLayout(jd_Producto.getContentPane());
        jd_Producto.getContentPane().setLayout(jd_ProductoLayout);
        jd_ProductoLayout.setHorizontalGroup(
            jd_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ProductoLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jd_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(110, 110, 110)
                .addGroup(jd_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tf_IDProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                        .addComponent(tf_Marca)
                        .addComponent(tf_Material))
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(217, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_ProductoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jd_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_ProductoLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(312, 312, 312))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_ProductoLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))))
        );
        jd_ProductoLayout.setVerticalGroup(
            jd_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ProductoLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel12)
                .addGap(107, 107, 107)
                .addGroup(jd_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tf_IDProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(101, 101, 101)
                .addGroup(jd_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tf_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90)
                .addGroup(jd_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tf_Material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addGroup(jd_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jLabel17.setFont(new java.awt.Font("MS UI Gothic", 0, 48)); // NOI18N
        jLabel17.setText("Crear Maquina");

        jLabel18.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        jLabel18.setText("Numero Serie");

        tf_NumSerie.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N

        jLabel19.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        jLabel19.setText("Estado Maquina");

        cb_Estado.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        cb_Estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bueno", "Malo" }));

        jLabel20.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        jLabel20.setText("ID Placa");

        tf_IDPlaca.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N

        jLabel21.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        jLabel21.setText("ID Carcasa");

        tf_IDCarcasa.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N

        jLabel22.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        jLabel22.setText("Numero Reparaciones");

        tf_NumReparacion.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N

        bt_AgregarMaquina.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        bt_AgregarMaquina.setText("Agreagar");

        javax.swing.GroupLayout jd_MaquinaLayout = new javax.swing.GroupLayout(jd_Maquina.getContentPane());
        jd_Maquina.getContentPane().setLayout(jd_MaquinaLayout);
        jd_MaquinaLayout.setHorizontalGroup(
            jd_MaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_MaquinaLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addGroup(jd_MaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addGap(65, 65, 65)
                .addGroup(jd_MaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_NumSerie)
                    .addComponent(cb_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_IDPlaca)
                    .addComponent(tf_IDCarcasa)
                    .addComponent(tf_NumReparacion, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_MaquinaLayout.createSequentialGroup()
                .addContainerGap(510, Short.MAX_VALUE)
                .addGroup(jd_MaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_MaquinaLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(496, 496, 496))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_MaquinaLayout.createSequentialGroup()
                        .addComponent(bt_AgregarMaquina, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(198, 198, 198))))
        );
        jd_MaquinaLayout.setVerticalGroup(
            jd_MaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_MaquinaLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel17)
                .addGap(135, 135, 135)
                .addGroup(jd_MaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tf_NumSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(jd_MaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(cb_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(jd_MaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(tf_IDPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(jd_MaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(tf_IDCarcasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(jd_MaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(tf_NumReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(bt_AgregarMaquina, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel23.setFont(new java.awt.Font("MS UI Gothic", 0, 48)); // NOI18N
        jLabel23.setText("Tecnico");

        jLabel24.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        jLabel24.setText("Id Tecnico");

        jLabel25.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        jLabel25.setText("Nombre");

        jLabel26.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        jLabel26.setText("Porcentaje Fallo");

        jLabel27.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        jLabel27.setText("Numero Reparaciones");

        tf_IDTecnico.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N

        tf_NomTecnico.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N

        tf_NumRepTecnico.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N

        bt_AgregarTecnico.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        bt_AgregarTecnico.setText("Agregar");

        sp_Fallo.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N

        javax.swing.GroupLayout jd_TecnicoLayout = new javax.swing.GroupLayout(jd_Tecnico.getContentPane());
        jd_Tecnico.getContentPane().setLayout(jd_TecnicoLayout);
        jd_TecnicoLayout.setHorizontalGroup(
            jd_TecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_TecnicoLayout.createSequentialGroup()
                .addGroup(jd_TecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_TecnicoLayout.createSequentialGroup()
                        .addGap(556, 556, 556)
                        .addComponent(jLabel23))
                    .addGroup(jd_TecnicoLayout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addGroup(jd_TecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(115, 115, 115)
                        .addGroup(jd_TecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_NomTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_NumRepTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_IDTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sp_Fallo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(414, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_TecnicoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bt_AgregarTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(260, 260, 260))
        );

        jd_TecnicoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel24, jLabel25, jLabel26, jLabel27});

        jd_TecnicoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tf_IDTecnico, tf_NomTecnico, tf_NumRepTecnico});

        jd_TecnicoLayout.setVerticalGroup(
            jd_TecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_TecnicoLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel23)
                .addGap(122, 122, 122)
                .addGroup(jd_TecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(tf_IDTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(jd_TecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(tf_NomTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(jd_TecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(sp_Fallo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(jd_TecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(tf_NumRepTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86)
                .addComponent(bt_AgregarTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jLabel28.setFont(new java.awt.Font("MS UI Gothic", 0, 48)); // NOI18N
        jLabel28.setText("Orden de Reparación");

        jLabel29.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        jLabel29.setText("ID Tecnico");

        jLabel30.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        jLabel30.setText("Numero de Serie");

        bt_AgregarReparacion.setText("Agregar");

        cb_IDTecnico.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N

        cb_NumReparaciones.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N

        javax.swing.GroupLayout jd_ReparacionLayout = new javax.swing.GroupLayout(jd_Reparacion.getContentPane());
        jd_Reparacion.getContentPane().setLayout(jd_ReparacionLayout);
        jd_ReparacionLayout.setHorizontalGroup(
            jd_ReparacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ReparacionLayout.createSequentialGroup()
                .addGroup(jd_ReparacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ReparacionLayout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel28))
                    .addGroup(jd_ReparacionLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(jd_ReparacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30))
                        .addGap(112, 112, 112)
                        .addGroup(jd_ReparacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_IDTecnico, 0, 210, Short.MAX_VALUE)
                            .addComponent(cb_NumReparaciones, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(281, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_ReparacionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bt_AgregarReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
        );
        jd_ReparacionLayout.setVerticalGroup(
            jd_ReparacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ReparacionLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel28)
                .addGap(110, 110, 110)
                .addGroup(jd_ReparacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(cb_IDTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addGroup(jd_ReparacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(cb_NumReparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(108, 108, 108)
                .addComponent(bt_AgregarReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jLabel31.setFont(new java.awt.Font("MS UI Gothic", 0, 48)); // NOI18N
        jLabel31.setText("Alquiler de Maquina");

        jLabel32.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        jLabel32.setText("Numero de Serie");

        jLabel33.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        jLabel33.setText("Numero Comercio");

        cb_SerieAlquiler.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N

        cb_ComercioAlquiler.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N

        bt_AgregarAlquiler.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        bt_AgregarAlquiler.setText("Agregar");

        javax.swing.GroupLayout jd_AlquilerLayout = new javax.swing.GroupLayout(jd_Alquiler.getContentPane());
        jd_Alquiler.getContentPane().setLayout(jd_AlquilerLayout);
        jd_AlquilerLayout.setHorizontalGroup(
            jd_AlquilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_AlquilerLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jd_AlquilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33))
                .addGap(104, 104, 104)
                .addGroup(jd_AlquilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cb_SerieAlquiler, 0, 180, Short.MAX_VALUE)
                    .addComponent(cb_ComercioAlquiler, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_AlquilerLayout.createSequentialGroup()
                .addContainerGap(228, Short.MAX_VALUE)
                .addGroup(jd_AlquilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_AlquilerLayout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addGap(194, 194, 194))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_AlquilerLayout.createSequentialGroup()
                        .addComponent(bt_AgregarAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))))
        );
        jd_AlquilerLayout.setVerticalGroup(
            jd_AlquilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_AlquilerLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel31)
                .addGap(107, 107, 107)
                .addGroup(jd_AlquilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(cb_SerieAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jd_AlquilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(cb_ComercioAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(bt_AgregarAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INICIO");

        jLabel1.setFont(new java.awt.Font("MS UI Gothic", 1, 48)); // NOI18N
        jLabel1.setText("Compañia de Ensamblaje");

        jb_Proveedor.setFont(new java.awt.Font("MS UI Gothic", 0, 36)); // NOI18N
        jb_Proveedor.setText("Proveedor");
        jb_Proveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ProveedorMouseClicked(evt);
            }
        });

        jb_Producto.setFont(new java.awt.Font("MS UI Gothic", 0, 36)); // NOI18N
        jb_Producto.setText("Producto");
        jb_Producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ProductoMouseClicked(evt);
            }
        });

        jb_Comercio.setFont(new java.awt.Font("MS UI Gothic", 0, 36)); // NOI18N
        jb_Comercio.setText("Comercio");
        jb_Comercio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ComercioMouseClicked(evt);
            }
        });

        jb_Tecnico.setFont(new java.awt.Font("MS UI Gothic", 0, 36)); // NOI18N
        jb_Tecnico.setText("Tecnico");
        jb_Tecnico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_TecnicoMouseClicked(evt);
            }
        });

        jb_Maquina.setFont(new java.awt.Font("MS UI Gothic", 0, 36)); // NOI18N
        jb_Maquina.setText("Maquina");
        jb_Maquina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_MaquinaMouseClicked(evt);
            }
        });

        jb_Reparacion.setFont(new java.awt.Font("MS UI Gothic", 0, 36)); // NOI18N
        jb_Reparacion.setText("Orden  Reparación");
        jb_Reparacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ReparacionMouseClicked(evt);
            }
        });

        jb_Alquiler.setFont(new java.awt.Font("MS UI Gothic", 0, 36)); // NOI18N
        jb_Alquiler.setText("Alquiler de  Maquina");
        jb_Alquiler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_AlquilerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(571, 571, 571))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jb_Proveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jb_Producto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(404, 404, 404)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jb_Tecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(205, 205, 205)
                                .addComponent(jb_Reparacion))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jb_Comercio)
                                .addGap(294, 294, 294)
                                .addComponent(jb_Maquina))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(645, 645, 645)
                        .addComponent(jb_Alquiler)))
                .addContainerGap(243, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel1)
                .addGap(149, 149, 149)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_Proveedor)
                    .addComponent(jb_Comercio)
                    .addComponent(jb_Maquina))
                .addGap(153, 153, 153)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_Producto)
                    .addComponent(jb_Tecnico)
                    .addComponent(jb_Reparacion))
                .addGap(103, 103, 103)
                .addComponent(jb_Alquiler)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_AgregarProvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_AgregarProvMouseClicked
        InsertarProveedor();
    }//GEN-LAST:event_jb_AgregarProvMouseClicked

    private void jb_ProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ProveedorMouseClicked
        jd_Proveedor.pack();
        jd_Proveedor.setModal(true);
        jd_Proveedor.setVisible(true);
        jd_Proveedor.setLocationRelativeTo(null);
    }//GEN-LAST:event_jb_ProveedorMouseClicked

    private void jb_ComercioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ComercioMouseClicked
        jd_Comercio.pack();
        jd_Comercio.setModal(true);
        jd_Comercio.setVisible(true);
        jd_Comercio.setLocationRelativeTo(null);
    }//GEN-LAST:event_jb_ComercioMouseClicked

    private void cb_ProveeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_ProveeActionPerformed
        if (cb_Provee.getSelectedIndex() == 1) {
            sp_Ingreso.setEnabled(false);
        } else {
            sp_Ingreso.setEnabled(true);
        }
    }//GEN-LAST:event_cb_ProveeActionPerformed

    private void jb_AgregarComercioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_AgregarComercioMouseClicked
        InsertarComercio();
    }//GEN-LAST:event_jb_AgregarComercioMouseClicked

    private void jb_ProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ProductoMouseClicked
        jd_Producto.pack();
        jd_Producto.setModal(true);
        jd_Producto.setVisible(true);
        jd_Producto.setLocationRelativeTo(null);
    }//GEN-LAST:event_jb_ProductoMouseClicked

    private void jb_MaquinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_MaquinaMouseClicked
        jd_Maquina.pack();
        jd_Maquina.setModal(true);
        jd_Maquina.setVisible(true);
        jd_Maquina.setLocationRelativeTo(null);
    }//GEN-LAST:event_jb_MaquinaMouseClicked

    private void jb_TecnicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_TecnicoMouseClicked
        jd_Tecnico.pack();
        jd_Tecnico.setModal(true);
        jd_Tecnico.setVisible(true);
        jd_Tecnico.setLocationRelativeTo(null);
    }//GEN-LAST:event_jb_TecnicoMouseClicked

    private void jb_ReparacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ReparacionMouseClicked
        jd_Reparacion.pack();
        jd_Reparacion.setModal(true);
        jd_Reparacion.setVisible(true);
        jd_Reparacion.setLocationRelativeTo(null);
    }//GEN-LAST:event_jb_ReparacionMouseClicked

    private void jb_AlquilerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_AlquilerMouseClicked
        jd_Alquiler.pack();
        jd_Alquiler.setModal(true);
        jd_Alquiler.setVisible(true);
        jd_Alquiler.setLocationRelativeTo(null);
    }//GEN-LAST:event_jb_AlquilerMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_AgregarAlquiler;
    private javax.swing.JButton bt_AgregarMaquina;
    private javax.swing.JButton bt_AgregarReparacion;
    private javax.swing.JButton bt_AgregarTecnico;
    private javax.swing.JComboBox<String> cb_ComercioAlquiler;
    private javax.swing.JComboBox<String> cb_Estado;
    private javax.swing.JComboBox<String> cb_IDTecnico;
    private javax.swing.JComboBox<String> cb_NumReparaciones;
    private javax.swing.JComboBox<String> cb_Provee;
    private javax.swing.JComboBox<String> cb_Proveedor;
    private javax.swing.JComboBox<String> cb_SerieAlquiler;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jb_AgregarComercio;
    private javax.swing.JButton jb_AgregarProv;
    private javax.swing.JButton jb_Alquiler;
    private javax.swing.JButton jb_Comercio;
    private javax.swing.JButton jb_Maquina;
    private javax.swing.JButton jb_Producto;
    private javax.swing.JButton jb_Proveedor;
    private javax.swing.JButton jb_Reparacion;
    private javax.swing.JButton jb_Tecnico;
    private javax.swing.JDialog jd_Alquiler;
    private javax.swing.JDialog jd_Comercio;
    private javax.swing.JDialog jd_Maquina;
    private javax.swing.JDialog jd_Producto;
    private javax.swing.JDialog jd_Proveedor;
    private javax.swing.JDialog jd_Reparacion;
    private javax.swing.JDialog jd_Tecnico;
    private javax.swing.JSpinner sp_Fallo;
    private javax.swing.JSpinner sp_Ingreso;
    private javax.swing.JTextField tf_IDCarcasa;
    private javax.swing.JTextField tf_IDPlaca;
    private javax.swing.JTextField tf_IDProducto;
    private javax.swing.JTextField tf_IDTecnico;
    private javax.swing.JTextField tf_IdProveedor;
    private javax.swing.JTextField tf_Marca;
    private javax.swing.JTextField tf_Material;
    private javax.swing.JTextField tf_NomComercio;
    private javax.swing.JTextField tf_NomTecnico;
    private javax.swing.JTextField tf_NombreProv;
    private javax.swing.JTextField tf_NumComercio;
    private javax.swing.JTextField tf_NumRepTecnico;
    private javax.swing.JTextField tf_NumReparacion;
    private javax.swing.JTextField tf_NumSerie;
    private javax.swing.JTextField tf_Recaudacion;
    // End of variables declaration//GEN-END:variables

    private void InsertarProveedor() {
        Connection cn;
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            cn = DriverManager.getConnection(cadena, usuario, pass);
            CallableStatement csta = cn.prepareCall("{call Pro_Proveedor(?,?,?,?,?)}");
            csta.setInt(1, Integer.parseInt(tf_IdProveedor.getText()));
            csta.setString(2, tf_NombreProv.getText());
            if (cb_Proveedor.getSelectedIndex() == 0) {
                csta.setBoolean(3, true);
                csta.setBoolean(4, false);
            } else {
                csta.setBoolean(3, false);
                csta.setBoolean(4, true);
            }
            csta.setString(5, String.valueOf('I'));
            csta.execute();
            System.out.println("Exito");
        } catch (Exception e) {
            //e.printStackTrace();
            while (e.getMessage().contains("PRIMARY")) {
                try {
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    cn = DriverManager.getConnection(cadena, usuario, pass);
                    CallableStatement csta = cn.prepareCall("{call Pro_Proveedor(?,?,?,?,?)}");
                    int id = Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese una id valida", "ERROR", INFORMATION_MESSAGE));
                    csta.setInt(1, id);
                    csta.setString(2, tf_NombreProv.getText());
                    if (cb_Proveedor.getSelectedIndex() == 0) {
                        csta.setBoolean(3, true);
                        csta.setBoolean(4, false);
                    } else {
                        csta.setBoolean(3, false);
                        csta.setBoolean(4, true);
                    }
                    csta.setString(5, String.valueOf('I'));
                    csta.execute();
                    System.out.println("Exito2");
                    break;
                } catch (Exception n) {
                    e = n;
                }
            }
        }
    }/*chequeeeee*/

    private void InsertarComercio() {
        Connection cn;
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            cn = DriverManager.getConnection(cadena, usuario, pass);
            CallableStatement csta = cn.prepareCall("{call Pro_Comercio(?,?,?,?,?,?,?,?)}");
            csta.setInt(1, Integer.parseInt(tf_NumComercio.getText()));
            csta.setString(2, tf_NomComercio.getText());
            csta.setDouble(3, Double.parseDouble(tf_Recaudacion.getText()));
            System.out.println("aja");
            if (cb_Provee.getSelectedIndex() == 0) {
                csta.setBoolean(4, true);
                csta.setDouble(5, (Double.parseDouble(tf_Recaudacion.getText()) * (Integer) sp_Ingreso.getValue()) / 100);
                csta.setBoolean(6, false);
                System.out.println("entra1");
            } else {
                csta.setBoolean(4, false);
                csta.setDouble(5, Double.parseDouble(tf_Recaudacion.getText()));
                csta.setBoolean(6, true);
                System.out.println("entra2");
            }
            System.out.println("VALUE   " + sp_Ingreso.getValue());
            if ((Integer)sp_Ingreso.getValue() == 0) {
                csta.setDouble(7, 100);
            } else {
                csta.setDouble(7, (Integer) sp_Ingreso.getValue());
            }
            csta.setString(8, String.valueOf('I'));
            csta.execute();
            System.out.println("Exito");
        } catch (Exception e) {
            //e.printStackTrace();
            while (e.getMessage().contains("PRIMARY")) {
                try {
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    cn = DriverManager.getConnection(cadena, usuario, pass);
                    CallableStatement csta = cn.prepareCall("{call Pro_Comercio(?,?,?,?,?,?,?,?)}");
                    int id = Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese una id valida", "ERROR", INFORMATION_MESSAGE));
                    csta.setInt(1, id);
                    csta.setString(2, tf_NomComercio.getText());
                    csta.setDouble(3, Double.parseDouble(tf_Recaudacion.getText()));
                    if (cb_Provee.getSelectedIndex() == 0) {
                        csta.setBoolean(4, true);
                        csta.setDouble(5, (Double.parseDouble(tf_Recaudacion.getText()) * (Integer) sp_Ingreso.getValue()) / 100);
                        csta.setBoolean(6, false);
                    } else {
                        csta.setBoolean(4, false);
                        csta.setDouble(5, Double.parseDouble(tf_Recaudacion.getText()));
                        csta.setBoolean(6, true);
                    }
                    if ((Integer)sp_Ingreso.getValue() == 0) {
                        csta.setDouble(7, 100);
                    } else {
                        csta.setDouble(7, (Integer) sp_Ingreso.getValue());
                    }
                    csta.setString(8, String.valueOf('I'));
                    csta.execute();
                    System.out.println("Exito2");
                    break;
                } catch (Exception n) {
                    e = n;
                }
            }
        }
    }/*chequeeeee*/
    
    private void InsertarProducto(){
        Connection cn;
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            cn = DriverManager.getConnection(cadena, usuario, pass);
            CallableStatement csta = cn.prepareCall("{call Pro_Producto(?,?,?,?,?)}");
            csta.setInt(1, Integer.parseInt(tf_NumComercio.getText()));
            csta.setString(2, tf_NomComercio.getText());
            csta.setDouble(3, Double.parseDouble(tf_Recaudacion.getText()));
            if (cb_Provee.getSelectedIndex() == 0) {
                csta.setBoolean(4, true);
                csta.setDouble(5, (Double.parseDouble(tf_Recaudacion.getText()) * (Integer) sp_Ingreso.getValue()) / 100);
                csta.setBoolean(6, false);
                System.out.println("entra1");
            } else {
                csta.setBoolean(4, false);
                csta.setDouble(5, Double.parseDouble(tf_Recaudacion.getText()));
                csta.setBoolean(6, true);
                System.out.println("entra2");
            }
            System.out.println("VALUE   " + sp_Ingreso.getValue());
            if ((Integer)sp_Ingreso.getValue() == 0) {
                csta.setDouble(7, 100);
            } else {
                csta.setDouble(7, (Integer) sp_Ingreso.getValue());
            }
            csta.setString(8, String.valueOf('I'));
            csta.execute();
            System.out.println("Exito");
        } catch (Exception e) {
            //e.printStackTrace();
            while (e.getMessage().contains("PRIMARY")) {
                try {
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    cn = DriverManager.getConnection(cadena, usuario, pass);
                    CallableStatement csta = cn.prepareCall("{call Pro_Producto(?,?,?,?,?)}");
                    int id = Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese una id valida", "ERROR", INFORMATION_MESSAGE));
                    csta.setInt(1, id);
                    csta.setString(2, tf_NomComercio.getText());
                    csta.setDouble(3, Double.parseDouble(tf_Recaudacion.getText()));
                    if (cb_Provee.getSelectedIndex() == 0) {
                        csta.setBoolean(4, true);
                        csta.setDouble(5, (Double.parseDouble(tf_Recaudacion.getText()) * (Integer) sp_Ingreso.getValue()) / 100);
                        csta.setBoolean(6, false);
                    } else {
                        csta.setBoolean(4, false);
                        csta.setDouble(5, Double.parseDouble(tf_Recaudacion.getText()));
                        csta.setBoolean(6, true);
                    }
                    if ((Integer)sp_Ingreso.getValue() == 0) {
                        csta.setDouble(7, 100);
                    } else {
                        csta.setDouble(7, (Integer) sp_Ingreso.getValue());
                    }
                    csta.setString(8, String.valueOf('I'));
                    csta.execute();
                    System.out.println("Exito2");
                    break;
                } catch (Exception n) {
                    e = n;
                }
            }
        }
    }
}
